
-- create user table
CREATE TABLE users(

	meter_number integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	first_name varchar(50) not null,
	last_name varchar(50),
	user_address varchar(70),
	user_city varchar(20),
	user_state varchar(30),
	user_email varchar(30),
	user_phone_number varchar(15),
	user_type varchar(20)
)

-- create bill table
create table bills
(
	bill_number integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	bill_date date,
	bill_unit integer,
	bill_amount real,
	meter_number integer REFERENCES users(meter_number)
)

-- insert data in user table
INSERT INTO public.users(
	first_name, last_name, user_address, user_city, user_state, user_email, user_phone_number, user_type)
	VALUES ('Jugal','Patil','Pune', 'pune', 'Maharashtra', 'jugal@gmail.com', '8877989878','home');

-- insert data in bill table
INSERT INTO public.bills(
	bill_date, bill_unit, bill_amount, meter_number)
	VALUES ('2023-04-01', 100, 540, 2);

-- get match data from both tables
select u.meter_number , u.first_name ,u.user_type, b.bill_amount from users u
join bills b
on u.meter_number = b.meter_number


select u.meter_number ,b.bill_amount,b.bill_date from users u
join bills b
on u.meter_number = b.meter_number





create table rates
(
	rate_id integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	user_type character(20),
	user_price real,
	rate_min real,
	rate_max real
)

insert into rates (user_type,user_price,rate_min,rate_max)
values ('home',10,300,500),('home',15,500,0);

--
ALTER TABLE bills
ADD CONSTRAINT bill_date UNIQUE(bill_date);



CREATE TABLE IF NOT EXISTS public.admin
(
    admin_id integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    admin_username character(20) UNIQUE,
    admin_password character(20)

)



INSERT INTO public.admin(
	admin_username, admin_password)
	VALUES ('Test', 'test');

ALTER TABLE IF EXISTS public.rates
    ADD COLUMN user_price numeric;